Addition of tyaml's README + licensing disclaimer
Calebe94/pytools pull request #116
Opened 2021-03-09 12:56 UTC by gbgabo

PR focused on creating a first README of tyaml + disclaimer of licensing on the scripts source code header

2021-03-10 13:16 UTC, calebe94 requested changes
Just a change in the description

2021-03-10 13:16 UTC, calebe94 commented on tyaml/README.md
> +A simple script to get values on a yaml file.
"A simple script to parse a yaml file." Would be better.

2021-03-10 23:55 UTC, gbgabo commented on tyaml/README.md
> +A simple script to get values on a yaml file.
Indeed!
Just did it!

2021-03-11 02:22 UTC, Calebe94 approved these changes
Everithing seems OK!

2021-03-12 23:45 UTC, merged