Addition of tmenu's README + licensing disclaimer
Calebe94/pytools pull request #118
Opened 2021-03-12 02:03 UTC by gbgabo

PR focused on creating a first README of tyaml + disclaimer of licensing on the scripts source code header

2021-03-12 13:49 UTC, Calebe94 requested changes
Has to remove tyaml's changes.

2021-03-12 13:49 UTC, Calebe94 commented on tyaml/README.md
> +# `tyaml`
This file does not belongs in this PR.

2021-03-12 13:49 UTC, Calebe94 commented on tyaml/tyaml
> +#This file is part of the TinyTools distribution (https://github.com/Calebe94/TinyTools).
This change does not belong in this PR

2021-03-13 00:05 UTC, gbgabo commented
PR solves #4

2021-03-13 19:29 UTC, Calebe94 approved these changes
Everything seems OK to me.

2021-03-15 19:43 UTC, merged